from selenium.webdriver.common.by import By
class OrderFeedLocators:
    ORDER_FEED = (By.XPATH, ".//p[text() = 'Лента Заказов']")
    ORDER = (By.XPATH, ".//a[@class = 'OrderHistory_link__1iNby']")
    MODAL_WINDOW = (By.XPATH, '(//div[contains(@class, "Modal_orderBox__1xWdi")])')
    COMPOUND = (By.XPATH, ".//p[contains(text(),'Cостав')]")
    PERSONAL_AREA = (By.XPATH, ".//p[text() = 'Личный Кабинет']")
    LOGIN_BUTTON = (By.XPATH, ".//button[text() = 'Войти']")
    Email = (By.XPATH, ".//input[@name='name']")
    PASSWORD = (By.XPATH, ".//input[@name = 'Пароль']")
    MAKE_ORDER = (By.XPATH, ".//button[text() = 'Оформить заказ']")
    ADD_TO_ORDER = (By.XPATH, ".//ul[@class = 'BurgerConstructor_basket__list__l9dp_']")
    INGREDIENT_MOVE = (By.XPATH, ".//img[@alt = 'Флюоресцентная булка R2-D3']")
    ORDER_IDENTIFIER = (By.XPATH, ".//p[text() = 'идентификатор заказа']")
    CLOSE_WINDOW = (By.XPATH, ".//button[@class = 'Modal_modal__close_modified__3V5XS Modal_modal__close__TnseK']")
    HISTORY_ORDERS = (By.XPATH, ".//a[text() = 'История заказов']")
    SAVE_BUTTON = (By.XPATH, ".//button[text() = 'Сохранить']")
    ORDER_IN_LIST = (By.XPATH, ".//a[@class = 'OrderHistory_link__1iNby']")
    FIND_ORDER = (By.XPATH, ".//div[@class = 'OrderHistory_textBox__3lgbs mb-6']")
    NUMBER_ORDER = (By.XPATH, ".//p[@class = 'text text_type_digits-default']")
    CLOSE_WINDOW_ORDER = (By.XPATH, ".//button[@class = 'Modal_modal_overlay__x2ZCr']")
    NUMBER_ORDER_IN_FEED = (By.XPATH, ".//p[@class = 'text text_type_digits-default']")
    COMPLETED_FOR_ALL_TIME = (By.XPATH, ".//p[contains(@class,'OrderFeed_number__2MbrQ')]")
    TRANSLATOR_TUB = (By.XPATH, ".//p[text() = 'Конструктор']")
    NUM_ORDER = (By.XPATH, ".//h2[contains(@class,'Modal_modal__title_shadow__3ikwq')]")
    NUM_ORDER_IN_WORK = (By.XPATH, ".//ul[contains(@class,'OrderFeed_orderListReady__1YFem')]")
    LIST_ORDERS_IN_WORK = (By.XPATH, ".//li[contains(@class,'text_type_digits-default')]")